<?php

namespace AppBundle\Repository;

/**
 * adeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adeaRepository extends \Doctrine\ORM\EntityRepository
{
}
