<?php

namespace AppBundle\Repository;

/**
 * attachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
