<?php

namespace AppBundle\Repository;

/**
 * ideaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ideaRepository extends \Doctrine\ORM\EntityRepository
{
}
