<?php

namespace AppBundle\Repository;

/**
 * invitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invitationRepository extends \Doctrine\ORM\EntityRepository
{
}
