<?php

namespace AppBundle\Repository;

/**
 * notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notificationRepository extends \Doctrine\ORM\EntityRepository
{
}
