<?php

namespace AppBundle\Repository;

/**
 * signalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class signalisationRepository extends \Doctrine\ORM\EntityRepository
{
}
